//! Bridge from a Cloche presentation style to a HyperFrames `DESIGN.md`.
//!
//! Cloche's whole identity is the gradient `shot-card` produced by `polish` /
//! `capture`. A reel rendered with the HyperFrames engine should look like the
//! same product, so we translate the chosen [`PresentationStyle`] palette into
//! the brand cheat-sheet HyperFrames expects (its "Visual Identity Gate" reads
//! `## Style Prompt`, `## Colors`, `## Typography`, `## What NOT to Do`). The
//! still card and the motion reel then trace back to one palette.

use crate::polish::PresentationStyle;

/// Lowercase `#rrggbb` for an RGB triple.
pub fn hex(rgb: [u8; 3]) -> String {
    format!("#{:02x}{:02x}{:02x}", rgb[0], rgb[1], rgb[2])
}

/// The light foreground used across Cloche cards and the reel canvas.
pub const CANVAS_TEXT: &str = "#f8fbff";

/// The font stack shared by the reel composition and this brand sheet. Kept to
/// Inter (which HyperFrames auto-embeds) plus a generic fallback; system-font
/// keywords like `-apple-system` are not auto-resolvable and break the render.
pub const FONT_STACK: &str = "Inter, sans-serif";

/// Build a HyperFrames `DESIGN.md` from a Cloche presentation style, so a
/// rendered reel shares the exact palette of the still `shot-card`.
pub fn design_md(style: &PresentationStyle, title: &str) -> String {
    let bg_deep = hex(style.stops[0]);
    let bg_mid = hex(style.stops[1]);
    let surface = hex(style.stops[2]);
    let glow_primary = hex(style.glow_a);
    let glow_secondary = hex(style.glow_b);

    format!(
        "# DESIGN.md\n\
\n\
Generated by Cloche from the `{palette}` presentation palette (seed `{seed}`).\n\
This is the brand cheat-sheet for `{title}` so the reel matches the still \
`shot-card`.\n\
\n\
## Style Prompt\n\
\n\
A polished, glass-cloche presentation: a deep `{bg_deep}` to `{bg_mid}` gradient \
canvas with a framed surface in `{surface}`, lifted by soft `{glow_primary}` and \
`{glow_secondary}` glows behind the content. Light `{text}` typography, generous \
padding, rounded corners, and layered shadows. Calm, confident, product-grade. \
Motion is smooth and unhurried, never frantic.\n\
\n\
## Colors\n\
\n\
- `{bg_deep}` - canvas background, deep gradient start\n\
- `{bg_mid}` - canvas background, gradient mid\n\
- `{surface}` - framed surface / gradient end, card chrome accent\n\
- `{glow_primary}` - primary glow and highlight accent\n\
- `{glow_secondary}` - secondary glow accent\n\
- `{text}` - foreground text on the dark canvas\n\
\n\
## Typography\n\
\n\
- `{font}` - all headings, captions, and body. Heavy weights (700-900) for \
display, tabular-nums on any numbers.\n\
\n\
## What NOT to Do\n\
\n\
- Do not introduce colors outside this palette; adjust an existing hex for \
contrast instead of inventing one.\n\
- Do not use full-screen linear gradients on the dark canvas (H.264 banding); \
prefer radial or solid plus a localized glow.\n\
- Do not use generic defaults (`#333`, `#3b82f6`, `Roboto`).\n\
- Do not let motion get frantic; keep entrances smooth and staggered.\n",
        palette = style.palette_name,
        seed = style.seed,
        title = title,
        bg_deep = bg_deep,
        bg_mid = bg_mid,
        surface = surface,
        glow_primary = glow_primary,
        glow_secondary = glow_secondary,
        text = CANVAS_TEXT,
        font = FONT_STACK,
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::polish;

    #[test]
    fn hex_formats_lowercase_padded() {
        assert_eq!(hex([0, 0, 0]), "#000000");
        assert_eq!(hex([255, 255, 255]), "#ffffff");
        assert_eq!(hex([49, 29, 130]), "#311d82");
    }

    #[test]
    fn design_md_has_the_four_hyperframes_sections() {
        let style = polish::style_with_palette(7, "aurora-teal").expect("known palette");
        let md = design_md(&style, "My Reel");
        assert!(md.contains("## Style Prompt"));
        assert!(md.contains("## Colors"));
        assert!(md.contains("## Typography"));
        assert!(md.contains("## What NOT to Do"));
    }

    #[test]
    fn design_md_carries_the_palette_hexes_and_title() {
        let style = polish::style_with_palette(7, "aurora-teal").expect("known palette");
        let md = design_md(&style, "Launch Day");
        // aurora-teal stops[0] = [10, 72, 92]
        assert!(md.contains("#0a485c"));
        assert!(md.contains("aurora-teal"));
        assert!(md.contains("Launch Day"));
        assert!(md.contains(CANVAS_TEXT));
    }
}
